### PR TITLE
Adds adam hogge as member

### PR DESCRIPTION
**Pull request by adamdiy**
## What is your full name?

Adam Hogge

## Which cohort did you graduate from?

FAC 3

## Have you attended two business meetings?

No

## If so, what were the dates? (You only have to name two)

(Before FAC3)

(looking forward to attending next one in person!)

### CODE REVIEW

**Comment by adamdiy** [comment]
updated, @NataliaLKB, let me know if I've done correctly B)

**Comment by NataliaLKB** [comment]
Thanks @adamdiy !

**Comment by claireinez** [comment]
@NataliaLKB I think this shouldn't have been merged until the next business meeting that @adamdiy attends :)

**Comment by NataliaLKB** [comment]
Haha thanks @claireinez ! I was in another meeting and clearly too tired to multi task. In future, you should just revert.

**Comment by NataliaLKB** [comment]
Sorry @adamdiy ! I will raise this again and see you at the next meeting

**Comment by claireinez** [comment]
@NataliaLKB I would have but I saw it on my phone and didn't trust myself to do it on a phone :laughing:

**Pull request merged**
