### PR TITLE
Add May Business meeting minutes

### PR DESCRIPTION
**Pull request by NataliaLKB**
We just finished our May business meeting, these are our minutes. Let me know if I missed anything!

### CODE REVIEW

**Comment by claireinez** [comment]
The only other thing is that we decided that we would cover which membership PRs will be merged that day at the start of the business meeting, so that people attending know for sure that they are eligible to vote.

**Comment by NataliaLKB** [comment]
Good shout @claireinez ! I will add that bit to the notes as well

**Comment by claireinez** [comment]
Looks good! @sofer please merge if you approve.

**Comment by claireinez** [comment]
:+1:

**Pull request merged**
